CREATE USER 'gerente'@'localhost' IDENTIFIED BY '0gGiOjvwsBRHnpdt';
CREATE USER 'empleado'@'localhost' IDENTIFIED BY 'F3sycVEqp9rrdCjt';
CREATE USER 'cliente_registrado'@'localhost' IDENTIFIED BY 'VApxJBYwnfHRuv43';
CREATE USER 'cliente_no_registrado'@'localhost' IDENTIFIED BY 'lgfCaXeEgEarShYu';

GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Cliente TO 'gerente'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Personal TO 'gerente'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Camarero TO 'gerente'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Chef_Ejecutivo TO 'gerente'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Gerente_General TO 'gerente'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Producto TO 'gerente'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Stock TO 'gerente'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Stock_Cantidad TO 'gerente'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Mesa TO 'gerente'@'localhost';
GRANT SELECT, INSERT, UPDATE ON lostrestanosdb.Reserva TO 'gerente'@'localhost';
GRANT SELECT, INSERT, UPDATE ON lostrestanosdb.Pedido TO 'gerente'@'localhost';
GRANT SELECT ON lostrestanosdb.Consume TO 'gerente'@'localhost';
GRANT SELECT ON lostrestanosdb.Datos_Usuarios TO 'gerente'@'localhost';
GRANT SELECT ON lostrestanosdb.Cliente TO 'empleado'@'localhost';
GRANT SELECT ON lostrestanosdb.Empresa TO 'gerente'@'localhost';
GRANT SELECT ON lostrestanosdb.Empresa_Ubicacion TO 'gerente'@'localhost';
GRANT SELECT ON lostrestanosdb.Empresa_Telefono TO 'gerente'@'localhost';
GRANT SELECT ON lostrestanosdb.Empresa_Horario TO 'gerente'@'localhost';

GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Pedido TO 'empleado'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Contiene TO 'empleado'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Efectua TO 'empleado'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Mesa TO 'empleado'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Producto TO 'empleado'@'localhost';
GRANT SELECT, UPDATE, DELETE, INSERT ON lostrestanosdb.Posee TO 'empleado'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Reserva TO 'empleado'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.No_Show TO 'empleado'@'localhost';
GRANT SELECT, DELETE, INSERT ON lostrestanosdb.Consume TO 'empleado'@'localhost';
GRANT SELECT, UPDATE ON lostrestanosdb.Stock_Cantidad TO 'empleado'@'localhost';
GRANT SELECT ON lostrestanosdb.Camarero TO 'empleado'@'localhost';
GRANT SELECT ON lostrestanosdb.Personal TO 'empleado'@'localhost';
GRANT SELECT ON lostrestanosdb.Cliente_Alergia TO 'empleado'@'localhost';
GRANT SELECT ON lostrestanosdb.Datos_Usuarios TO 'empleado'@'localhost';
GRANT SELECT ON lostrestanosdb.Stock TO 'empleado'@'localhost';
GRANT SELECT ON lostrestanosdb.Empresa TO 'empleado'@'localhost';
GRANT SELECT ON lostrestanosdb.Empresa_Ubicacion TO 'empleado'@'localhost';
GRANT SELECT ON lostrestanosdb.Empresa_Telefono TO 'empleado'@'localhost';
GRANT SELECT ON lostrestanosdb.Empresa_Horario TO 'empleado'@'localhost';

GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Reserva TO 'cliente_registrado'@'localhost';
GRANT UPDATE, SELECT ON lostrestanosdb.Cliente TO 'cliente_registrado'@'localhost';
GRANT UPDATE, SELECT ON lostrestanosdb.Personal TO 'cliente_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.Mesa TO 'cliente_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.Datos_Usuarios TO 'cliente_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.Producto TO 'cliente_registrado'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON lostrestanosdb.Comentario TO 'cliente_registrado'@'localhost';
GRANT EXECUTE ON PROCEDURE lostrestanosdb.Verificar_Comentario_Existente TO 'cliente_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.Pedido TO 'cliente_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.Empresa TO 'cliente_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.Empresa_Ubicacion TO 'cliente_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.Empresa_Telefono TO 'cliente_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.Empresa_Horario TO 'cliente_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.No_Show TO 'cliente_registrado'@'localhost';

GRANT SELECT, INSERT ON lostrestanosdb.Cliente TO 'cliente_no_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.Personal TO 'cliente_no_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.Producto TO 'cliente_no_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.Comentario TO 'cliente_no_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.Datos_Usuarios TO 'cliente_no_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.Empresa TO 'cliente_no_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.Empresa_Ubicacion TO 'cliente_no_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.Empresa_Telefono TO 'cliente_no_registrado'@'localhost';
GRANT SELECT ON lostrestanosdb.Empresa_Horario TO 'cliente_no_registrado'@'localhost';
GRANT EXECUTE ON PROCEDURE lostrestanosdb.Validar_SignUp_Cliente TO 'cliente_no_registrado'@'localhost';
GRANT EXECUTE ON PROCEDURE lostrestanosdb.Validar_SignIn_Cliente TO 'cliente_no_registrado'@'localhost';
GRANT EXECUTE ON PROCEDURE lostrestanosdb.Validar_SignIn_Personal TO 'cliente_no_registrado'@'localhost';