#!/bin/bash
LOGFILE="/var/log/tanos.log"

function init() {
    case $1 in
        -l | -list)
            echo "Listando procesos..."
            echo "[$(date)] Listando procesos" >> "$LOGFILE"
            ps aux | grep -E 'nftables|ssh|cron|crontab|dnf-automatic' | grep -v grep
            ;;
        -k | -kill)
            if [ -z "$2" ]; then
                echo "Por favor, especifique un PID para matar el proceso."
                exit 1
            fi
            echo "Matando el proceso con PID: $2"
            echo "[$(date)] Matando proceso PID: $2" >> "$LOGFILE"
            kill "$2"
            echo "Proceso $2 detenido."
            echo "[$(date)] Proceso $2 detenido" >> "$LOGFILE"
            ;;
        -s | -status)
            if [ -z "$2" ]; then
                echo "Por favor, especifique un PID para verificar su estado."
                exit 1
            fi
            echo "Verificando el estado del proceso con PID: $2"
            echo "[$(date)] Verificando estado proceso PID: $2" >> "$LOGFILE"
            ps -p "$2" -o pid,comm,state
            ;;
        -h | -help)
            echo "Uso: $0 [opción] [PID]"
            echo "[$(date)] Ayuda solicitada" >> "$LOGFILE"
            echo "Opciones:"
            echo "  -l, --list       Listar los procesos relacionados con nftables, ssh, cron, crontab y dnf-automatic"
            echo "  -k, --kill       Matar un proceso por su PID"
            echo "  -s, --status     Verificar el estado de un proceso por su PID"
            echo "  -h, --help       Mostrar este mensaje de ayuda"
            ;;
        *)
            echo "Opción no válida. Use -h o --help para ver las opciones disponibles."
            echo "[$(date)] Opción no válida" >> "$LOGFILE"
            exit 1
            ;;
    esac
}

init "$@"