#!/bin/bash

function init() {
    case "$1" in
        -r|--restore)
            echo "Restaurando los scripts a la última versión desde el repositorio..."
            cd /usr/local/bin || exit 1
            git clone --no-checkout https://github.com/J0ATx/Proyecto-Final-2025-Los3tanos.git
            cd /Proyecto-Final-2025-Los3tanos
            git sparse-checkout init --cone
            git sparse-checkout set tanos
            git checkout
}

# Tener en cuenta que se debe restaurar, por lo que bajar desde la ultima versión no sirve.

init "$@"