#!/bin/bash
LOGFILE="/var/log/tanos.log"

function init() {
    case $1 in
        -l | -list)
            echo "Listando servicios..."
            echo "[$(date)] Listando servicios" >> "$LOGFILE"
            systemctl list-units --type=service --all
            ;;
        -s | -status)
            if [ -z "$2" ]; then
                echo "Por favor, especifique un servicio para verificar su estado."
                exit 1
            fi
            echo "Verificando el estado del servicio: $2"
            echo "[$(date)] Verificando estado servicio: $2" >> "$LOGFILE"
            systemctl status "$2"
            ;;
        -r | -restart)
            if [ -z "$2" ]; then
                echo "Por favor, especifique un servicio para reiniciar."
                exit 1
            fi
            echo "Reiniciando el servicio: $2"
            echo "[$(date)] Reiniciando servicio: $2" >> "$LOGFILE"
            systemctl restart "$2"
            echo "Servicio $2 reiniciado."
            echo "[$(date)] Servicio $2 reiniciado" >> "$LOGFILE"
            ;;
        -k | -kill)
            if [ -z "$2" ]; then
                echo "Por favor, especifique un servicio para detener."
                exit 1
            fi
            echo "Deteniendo el servicio: $2"
            echo "[$(date)] Deteniendo servicio: $2" >> "$LOGFILE"
            systemctl stop "$2"
            echo "Servicio $2 detenido."
            echo "[$(date)] Servicio $2 detenido" >> "$LOGFILE"
            ;;
        -a | -active)
            echo "Listando servicios activos..."
            echo "[$(date)] Listando servicios activos" >> "$LOGFILE"
            systemctl list-units --type=service --state=active
            ;;
        -h | -help)
            echo "Uso: $0 [opción] [servicio]"
            echo "[$(date)] Ayuda solicitada" >> "$LOGFILE"
            echo "Opciones:"
            echo "  -l, --list       Listar todos los servicios"
            echo "  -s, --status     Verificar el estado de un servicio"
            echo "  -r, --restart    Reiniciar un servicio"
            echo "  -k, --kill       Detener un servicio"
            echo "  -a, --active     Listar servicios activos"
            echo "  -h, --help       Mostrar este mensaje de ayuda"
            ;;
        *)
            echo "Opción no válida. Use -h o --help para ver las opciones disponibles."
            echo "[$(date)] Opción no válida" >> "$LOGFILE"
            exit 1
            ;;
    esac
}

init "$@"