#!/bin/bash

function init() {
    echo "
          ██╗      ██████╗ ███████╗    ██████╗     ████████╗ █████╗ ███╗   ██╗ ██████╗ ███████╗          
          ██║     ██╔═══██╗██╔════╝    ╚════██╗    ╚══██╔══╝██╔══██╗████╗  ██║██╔═══██╗██╔════╝          
█████╗    ██║     ██║   ██║███████╗     █████╔╝       ██║   ███████║██╔██╗ ██║██║   ██║███████╗    █████╗
╚════╝    ██║     ██║   ██║╚════██║     ╚═══██╗       ██║   ██╔══██║██║╚██╗██║██║   ██║╚════██║    ╚════╝
          ███████╗╚██████╔╝███████║    ██████╔╝       ██║   ██║  ██║██║ ╚████║╚██████╔╝███████║          
          ╚══════╝ ╚═════╝ ╚══════╝    ╚═════╝        ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚══════╝          
"                                                            
    read -p "Ingrese su opción: " option

    case $option in
        -S | -services)
            servicios "$2"
            ;;
        -P | -processes)
            procesos "$2"
            ;;
        -N | -network)
            red "$2"
            ;;
        -L | -logs)
            registros "$2"
            ;;
        -U | -users)
            usuarios "$2"
            ;;
        -M | -monthly-backup)
            respaldo_mensual
            ;;
        -D | -daily-backup)
            respaldo_diario
            ;;
        -W | -weekly-backup)
            respaldo_semanal
            ;;
        -R | -restore)
            restauracion "$2"
            ;;
        -I | -install)
            instalacion "$2"
            ;;
        -E | -exit)
            echo "Saliendo..."
            exit 0
            ;;
        -H | -help)
            echo "Opciones disponibles:"
            echo "-S, -services: Operaciones de servicios"
            echo "-P, -processes: Operaciones de procesos"
            echo "-N, -network: Operaciones red"
            echo "-L, -logs: Operaciones registros"
            echo "-U, -users: Operaciones usuarios"
            echo "-M, -monthly-backup: Realizar respaldo mensual"
            echo "-D, -daily-backup: Realizar respaldo diario"
            echo "-W, -weekly-backup: Realizar respaldo semanal"
            echo "-R, -restore: Restaurar la aplicación"
            echo "-I, -install: Instalar o actualizar scripts"
            echo "-E, -exit: Salir del script"
            echo "-H, -help: Mostrar este mensaje de ayuda"
            ;;
        *)
            echo "Opción no válida. Por favor, intente de nuevo."
            init "$@"
            ;;
    esac
}

init "$@"