#!/bin/bash
LOGFILE="/var/log/tanos.log"

function init() {
    case $1 in
        -l | -list)
            echo "Listando usuarios..."
            echo "[$(date)] Listando usuarios" >> "$LOGFILE"
            getent passwd | grep -E '/bin/bash|/bin/sh|/bin/zsh' | awk -F: '{print $1}'
            ;;
        -a | -add)
            read -p "Ingrese el nombre del nuevo usuario: " username
            read -p "Ingrese el nombre completo del usuario: " fullname
            raed -p "Ingrese el grupo del usuario ('Operarios' o 'Administrativos'): " group
            read -s -p "Ingrese la contraseña para el usuario: " password
            echo
            sudo useradd -m -G "$group" "$username"
            echo "[$(date)] Usuario añadido: $username ($fullname, grupo: $group)" >> "$LOGFILE"
            sudo chfn -f "$fullname" "$username"
            sudo passwd "$username"
            ;;
        -d | -delete)
            read -p "Ingrese el nombre del usuario a eliminar: " username
            sudo deluser -r "$username"
            echo "[$(date)] Usuario eliminado: $username" >> "$LOGFILE"
            ;;
        -g | -groups)
            echo "Listando grupos..."
            echo "[$(date)] Listando grupos" >> "$LOGFILE"
            getent group | awk -F: '$3 >= 1000 {print $1}'
            ;;
        -h | -help)
            echo "Uso: $0 [opción]"
            echo "[$(date)] Ayuda solicitada" >> "$LOGFILE"
            echo "Opciones:"
            echo "  -l, --list       Listar los usuarios del sistema creados manualmente"
            echo "  -a, --add        Añadir un nuevo usuario"
            echo "  -d, --delete     Eliminar un usuario existente"
            echo "  -g, --groups     Listar los grupos del sistema creados manualmente"
            echo "  -h, --help       Mostrar este mensaje de ayuda"
            ;;
        *)
            echo "Opción no válida. Use -h o --help para ver las opciones disponibles."
            echo "[$(date)] Opción no válida" >> "$LOGFILE"
            exit 1
            ;;
    esac
}

init "$@"