#!/bin/bash

function init() {
    case "$1" in
        -v | --view)
            echo "Mostrando los últimos 10 registros:"
            tail -n 10 /var/log/tanos.log
            ;;
        -s | --search)
            if [ -z "$2" ]; then
                echo "Por favor, proporciona un término de búsqueda."
                exit 1
            fi
            echo "Buscando registros que contengan '$2':"
            grep "$2" /var/log/tanos.log
            ;;
        -a | --access)
            echo "Mostrando los últimos 10 registros de acceso:"
            tail -n 10 /var/log/auth.log
            ;;
        -h | --help)
            echo "Uso: $0 [opción]"
            echo "Opciones:"
            echo "  -v, --view     Ver los últimos 10 registros del centro de cómputos"
            echo "  -s, --search   Buscar registros del centro de cómputos que contengan un término específico"
            echo "  -a, --access   Ver los últimos 10 registros de acceso del sistema"
            echo "  -h, --help     Mostrar este mensaje de ayuda"
            ;;
        *)
            echo "Opción no válida. Use -h o --help para ver las opciones disponibles."
            exit 1
            ;;
    esac
}

init "$@"