#!/bin/bash

LOGFILE="/var/log/tanos.log"

BACKUP_DIR="/var/respaldos"
REMOTE_USER="arje"
REMOTE_HOST="192.168.0.0"
REMOTE_PATH="/var/respaldos/los3tanos"
DB_USER="root"
DB_PASS=""
DB_NAME="losTresTanosDB"
DATE=$(date +"%Y-%m-%d")

function init() {
    INCR_DIR="$BACKUP_DIR/diario"
    mkdir -p "$INCR_DIR"
    echo "[$(date)] Directorio de respaldo incremental creado: $INCR_DIR" >> "$LOGFILE"

    BACKUP_NAME="respaldo_incremental_diario_${DATE}"
    DB_BACKUP_NAME="${BACKUP_NAME}_db.sql.gz"
    FILES_BACKUP_NAME="${BACKUP_NAME}_files.tar.gz"
    SNAPSHOT_FILE="$BACKUP_DIR/semanal/gpc-snapshot.snar"

    mysqldump -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" | gzip > "$INCR_DIR/$DB_BACKUP_NAME"
    echo "[$(date)] Respaldo de base de datos realizado: $INCR_DIR/$DB_BACKUP_NAME" >> "$LOGFILE"

    tar --listed-incremental="$SNAPSHOT_FILE" -czpf "$INCR_DIR/$FILES_BACKUP_NAME" /etc --exclude="$BACKUP_DIR"
    echo "[$(date)] Respaldo incremental de archivos realizado: $INCR_DIR/$FILES_BACKUP_NAME" >> "$LOGFILE"

    sha256sum "$INCR_DIR/$DB_BACKUP_NAME" > "$INCR_DIR/$DB_BACKUP_NAME.sha256"
    echo "[$(date)] Checksum SHA256 generado para base de datos: $INCR_DIR/$DB_BACKUP_NAME.sha256" >> "$LOGFILE"

    sha256sum "$INCR_DIR/$FILES_BACKUP_NAME" > "$INCR_DIR/$FILES_BACKUP_NAME.sha256"
    echo "[$(date)] Checksum SHA256 generado para archivos: $INCR_DIR/$FILES_BACKUP_NAME.sha256" >> "$LOGFILE"

    scp "$INCR_DIR/$DB_BACKUP_NAME" "$INCR_DIR/$DB_BACKUP_NAME.sha256" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/"
    echo "[$(date)] Respaldo de base de datos transferido a remoto: $REMOTE_HOST:$REMOTE_PATH" >> "$LOGFILE"

    scp "$INCR_DIR/$FILES_BACKUP_NAME" "$INCR_DIR/$FILES_BACKUP_NAME.sha256" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/"
    echo "[$(date)] Respaldo de archivos transferido a remoto: $REMOTE_HOST:$REMOTE_PATH" >> "$LOGFILE"

    ssh "$REMOTE_USER@$REMOTE_HOST" "cd $REMOTE_PATH && \
        sha256sum -c $DB_BACKUP_NAME.sha256 && \
        sha256sum -c $FILES_BACKUP_NAME.sha256"

    if [ $? -eq 0 ]; then
        echo "[$(date)] Respaldo y verificación diarios completados correctamente" >> "$LOGFILE"
        exit 0
    else
        echo "[$(date)] Error en respaldo o verificación" >> "$LOGFILE"
        exit 1
    fi
}

# init "$@"