#!/bin/bash

LOGFILE="/var/log/tanos.log"

BACKUP_DIR="/var/respaldos"
REMOTE_USER="arje"
REMOTE_HOST="192.168.0.0"
REMOTE_PATH="/var/respaldos/los3tanos"
DB_USER="root"
DB_PASS=""
DB_NAME="losTresTanosDB"
DATE=$(date +"%Y-%m-%d")

function init() {
    FULL_DIR="$BACKUP_DIR/mensual"
    mkdir -p "$FULL_DIR"
    echo "[$(date)] Directorio de respaldo mensual creado: $FULL_DIR" >> "$LOGFILE"

    BACKUP_NAME="respaldo_completo_mensual_${DATE}"
    DB_BACKUP_NAME="${BACKUP_NAME}_db.sql.gz"
    FILES_BACKUP_NAME="${BACKUP_NAME}_files.tar.gz"
    SNAPSHOT_FILE="$FULL_DIR/gpc-snapshot.snar"

    rm -rf "$BACKUP_DIR/diario" "$BACKUP_DIR/semanal"
    rm -f "$BACKUP_DIR/semanal/gpc-snapshot.snar" "$BACKUP_DIR/diario/gpc-snapshot.snar"
    echo "[$(date)] Respaldos diario y semanal eliminados" >> "$LOGFILE"

    mysqldump -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" | gzip > "$FULL_DIR/$DB_BACKUP_NAME"
    echo "[$(date)] Respaldo de base de datos realizado: $DB_BACKUP_NAME" >> "$LOGFILE"

    tar --listed-incremental="$SNAPSHOT_FILE" -czpf "$FULL_DIR/$FILES_BACKUP_NAME" /etc --exclude="$BACKUP_DIR"
    echo "[$(date)] Respaldo de archivos realizado: $FILES_BACKUP_NAME" >> "$LOGFILE"

    sha256sum "$FULL_DIR/$DB_BACKUP_NAME" > "$FULL_DIR/$DB_BACKUP_NAME.sha256"
    echo "[$(date)] Checksum generado para base de datos: $DB_BACKUP_NAME.sha256" >> "$LOGFILE"

    sha256sum "$FULL_DIR/$FILES_BACKUP_NAME" > "$FULL_DIR/$FILES_BACKUP_NAME.sha256"
    echo "[$(date)] Checksum generado para archivos: $FILES_BACKUP_NAME.sha256" >> "$LOGFILE"

    scp "$FULL_DIR/$DB_BACKUP_NAME" "$FULL_DIR/$DB_BACKUP_NAME.sha256" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/"
    echo "[$(date)] Respaldo de base de datos transferido a remoto" >> "$LOGFILE"

    scp "$FULL_DIR/$FILES_BACKUP_NAME" "$FULL_DIR/$FILES_BACKUP_NAME.sha256" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/"
    echo "[$(date)] Respaldo de archivos transferido a remoto" >> "$LOGFILE"

    ssh "$REMOTE_USER@$REMOTE_HOST" "cd $REMOTE_PATH && \
        sha256sum -c $DB_BACKUP_NAME.sha256 && \
        sha256sum -c $FILES_BACKUP_NAME.sha256"

    if [ $? -eq 0 ]; then
        echo "[$(date)] Respaldo mensual completado exitosamente" >> "$LOGFILE"
        exit 0
    else
        echo "[$(date)] Error en respaldo mensual" >> "$LOGFILE"
        exit 1
    fi
}

# init "$@"