#!/bin/bash

LOGFILE="/var/log/tanos.log"

function init() {
    SRC_DIR="/usr/bin"
    BACKUP_DIR="/Respaldos"
    DATE=$(date +"%Y-%m-%d")
    INCR_DIR="$BACKUP_DIR/incremental"
    FULL_BACKUP="$BACKUP_DIR/full"
    SNAPSHOT_FILE="$BACKUP_DIR/rsync.snar"

    mkdir -p "$INCR_DIR" "$FULL_BACKUP"
    echo "[$(date)] Created backup directories: $INCR_DIR, $FULL_BACKUP" >> "$LOGFILE"

    if [ ! -f "$SNAPSHOT_FILE" ]; then
        tar --listed-incremental="$SNAPSHOT_FILE" -czpf "$FULL_BACKUP/full-$DATE.tar.gz" "$SRC_DIR"
        echo "[$(date)] Full backup created: $FULL_BACKUP/full-$DATE.tar.gz" >> "$LOGFILE"
    else
        tar --listed-incremental="$SNAPSHOT_FILE" -czpf "$INCR_DIR/incr-$DATE.tar.gz" "$SRC_DIR"
        echo "[$(date)] Incremental backup created: $INCR_DIR/incr-$DATE.tar.gz" >> "$LOGFILE"
    fi

    rsync -a --delete "$SRC_DIR/" "$BACKUP_DIR/rsync-latest/"
    echo "[$(date)] Rsync sync completed: $SRC_DIR to $BACKUP_DIR/rsync-latest/" >> "$LOGFILE"

    # Remote backup settings
    REMOTE_USER="your_remote_user"
    REMOTE_HOST="your.remote.server"
    REMOTE_DIR="/remote/backup/path"

    scp "$FULL_BACKUP/full-$DATE.tar.gz" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_DIR/" 2>/dev/null
    echo "[$(date)] Sent full backup to remote: $REMOTE_HOST:$REMOTE_DIR/" >> "$LOGFILE"

    if [ -f "$INCR_DIR/incr-$DATE.tar.gz" ]; then
        scp "$INCR_DIR/incr-$DATE.tar.gz" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_DIR/" 2>/dev/null
        echo "[$(date)] Sent incremental backup to remote: $REMOTE_HOST:$REMOTE_DIR/" >> "$LOGFILE"
    fi

    rsync -az --delete "$BACKUP_DIR/rsync-latest/" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_DIR/rsync-latest/"
    echo "[$(date)] Rsync backup directory synced to remote: $REMOTE_HOST:$REMOTE_DIR/rsync-latest/" >> "$LOGFILE"
}

init "$@"

# Usar dump para la base de datos.